"""empty message

Revision ID: 537c977e5121
Revises: 837eb2918b36
Create Date: 2021-02-24 03:13:37.960511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537c977e5121'
down_revision = '837eb2918b36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('firstName', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('lastName', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('note', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('phoneNumber', sa.String(length=13), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('service',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=60), nullable=False))
        batch_op.alter_column('service',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('phoneNumber')
        batch_op.drop_column('note')
        batch_op.drop_column('lastName')
        batch_op.drop_column('firstName')
        batch_op.drop_column('city')
        batch_op.drop_column('address')

    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)

    # ### end Alembic commands ###
