name: "Set Issue Label and Assignee"
on:
  issues:
    types: [opened, closed, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: anushkrishnav/issue-action
        with:
          title-or-body: "both"
          parameters: '[ {"assignees": ["username"]}]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
