name: Test Workflow
on:
  issues:
    types: [opened]

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: anushkrishnav/Issue-spam-blocker@master
      - name: Close Issue Action
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # default token in GitHub Workflow
          author: ${{ github.actor}}
